# Generated by Django 5.1 on 2024-09-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_aluno_alter_jogo_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hangman.professor'),
        ),
    ]
