# Generated by Django 4.2.16 on 2024-09-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hangman", "0004_remove_professor_user_alter_jogo_aluno_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jogo",
            name="aluno",
        ),
        migrations.AddField(
            model_name="jogo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
